"""Make contract software_id required

Revision ID: 11473ab5db73
Revises: 9b65b743672a
Create Date: 2026-08-30 16:12:14.039422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11473ab5db73'
down_revision = '9b65b743672a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('software_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('software_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
