"""Remove license_type from contracts

Revision ID: 1e0c0fd5423f
Revises: 921ad6913d0d
Create Date: 2026-08-31 19:18:02.996503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e0c0fd5423f'
down_revision = '921ad6913d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('license_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_type', mysql.VARCHAR(length=30), nullable=False))

    # ### end Alembic commands ###
