"""Rename Software model to License

Revision ID: 72e4f3e852eb
Revises: 9a8022bc8924
Create Date: 2026-08-31 20:43:01.746135

Hand-written, NOT autogenerated as-is: Alembic's autogenerate modeled this
as "drop table software" + "create table licenses", which would silently
discard every existing license, its contracts, and its school allocations.
This migration instead renames the table and its two dependent foreign-key
columns in place, so every existing row (and its id, still referenced by
contracts.license_id and license_allocations.license_id after the rename)
survives untouched.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72e4f3e852eb'
down_revision = '9a8022bc8924'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    is_mysql = bind.dialect.name == "mysql"

    # 1. Drop the FKs that point at software.id first, so neither the
    #    table rename nor the column renames below are blocked by them.
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint('contracts_ibfk_1', type_='foreignkey')
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.drop_constraint('license_allocations_ibfk_2', type_='foreignkey')

    # 2. Rename the table itself - every existing row keeps its id.
    op.rename_table('software', 'licenses')

    # 3. Rename the two FK columns that referenced it.
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('software_id', new_column_name='license_id',
                               existing_type=mysql.INTEGER())
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.alter_column('software_id', new_column_name='license_id',
                               existing_type=mysql.INTEGER())

    # 4. Cosmetic: rename indexes/constraints to match, so a future
    #    `flask db migrate` doesn't propose renaming them anyway.
    #    MySQL-only syntax (RENAME INDEX) - harmless to skip on other
    #    dialects since it doesn't affect data or functionality.
    if is_mysql:
        op.execute("ALTER TABLE licenses RENAME INDEX ix_software_name TO ix_licenses_name")
        op.execute("ALTER TABLE licenses RENAME INDEX ix_software_status TO ix_licenses_status")
        op.execute("ALTER TABLE licenses RENAME INDEX ix_software_vendor_id TO ix_licenses_vendor_id")
        op.execute("ALTER TABLE licenses RENAME INDEX ix_software_expiration_date TO ix_licenses_expiration_date")
        op.execute("ALTER TABLE contracts RENAME INDEX ix_contracts_software_id TO ix_contracts_license_id")
        op.execute(
            "ALTER TABLE license_allocations "
            "RENAME INDEX ix_license_allocations_software_id TO ix_license_allocations_license_id"
        )
        op.execute(
            "ALTER TABLE license_allocations "
            "RENAME INDEX uq_allocation_software_school TO uq_allocation_license_school"
        )

    # 5. Recreate the foreign keys against the renamed table/columns.
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_contracts_license_id_licenses', 'licenses', ['license_id'], ['id'])
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_license_allocations_license_id_licenses', 'licenses', ['license_id'], ['id']
        )


def downgrade():
    bind = op.get_bind()
    is_mysql = bind.dialect.name == "mysql"

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contracts_license_id_licenses', type_='foreignkey')
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_license_allocations_license_id_licenses', type_='foreignkey')

    if is_mysql:
        op.execute("ALTER TABLE licenses RENAME INDEX ix_licenses_name TO ix_software_name")
        op.execute("ALTER TABLE licenses RENAME INDEX ix_licenses_status TO ix_software_status")
        op.execute("ALTER TABLE licenses RENAME INDEX ix_licenses_vendor_id TO ix_software_vendor_id")
        op.execute("ALTER TABLE licenses RENAME INDEX ix_licenses_expiration_date TO ix_software_expiration_date")
        op.execute("ALTER TABLE contracts RENAME INDEX ix_contracts_license_id TO ix_contracts_software_id")
        op.execute(
            "ALTER TABLE license_allocations "
            "RENAME INDEX ix_license_allocations_license_id TO ix_license_allocations_software_id"
        )
        op.execute(
            "ALTER TABLE license_allocations "
            "RENAME INDEX uq_allocation_license_school TO uq_allocation_software_school"
        )

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('license_id', new_column_name='software_id',
                               existing_type=mysql.INTEGER())
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.alter_column('license_id', new_column_name='software_id',
                               existing_type=mysql.INTEGER())

    op.rename_table('licenses', 'software')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_foreign_key('contracts_ibfk_1', 'software', ['software_id'], ['id'])
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.create_foreign_key('license_allocations_ibfk_2', 'software', ['software_id'], ['id'])
