"""Restore NOT NULL on license_id columns after the rename

Revision ID: 74f2cc3f4150
Revises: 72e4f3e852eb
Create Date: 2026-08-31 20:45:53.560166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74f2cc3f4150'
down_revision = '72e4f3e852eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('license_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.alter_column('license_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_allocations', schema=None) as batch_op:
        batch_op.alter_column('license_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('license_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
