"""Flip Contract/License relationship: Contract owns Licenses

Revision ID: 7a1b4a3359c3
Revises: 74f2cc3f4150
Create Date: 2026-09-01 00:00:00.000000

Hand-written, NOT autogenerated as-is. The application's real workflow is
Vendor -> Contract -> License (one contract can bundle several licenses),
the reverse of the previous schema (Contract.license_id). Autogenerate
would model this as drop+recreate of both tables. This migration instead:

  1. Adds licenses.contract_id / licenses.annual_cost as nullable.
  2. Backfills every license from its existing (at most one) contract,
     copying that contract's annual_cost onto the license.
  3. For any license with no contract at all, synthesizes one from that
     license's own existing fields (vendor, po_number, dates) rather than
     inventing data, so contract_id can be made required afterward.
  4. Makes licenses.contract_id NOT NULL and adds its FK.
  5. Drops contracts.license_id and contracts.annual_cost (now redundant/
     moved).

The backfill loops row-by-row in Python (the dataset is small) rather than
a single multi-table UPDATE...JOIN, since that syntax isn't portable to
SQLite (used for local dev) even though this app currently runs on MySQL.

Every existing row keeps its id throughout - no table is dropped.
"""
from datetime import date, datetime, timedelta

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7a1b4a3359c3'
down_revision = '74f2cc3f4150'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    # 1. Add the new columns, nullable for now so existing rows aren't
    #    immediately rejected.
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annual_cost', sa.Numeric(precision=12, scale=2), nullable=True))

    licenses_t = sa.table(
        'licenses',
        sa.column('id', sa.Integer), sa.column('vendor_id', sa.Integer),
        sa.column('po_number', sa.String), sa.column('start_date', sa.Date),
        sa.column('expiration_date', sa.Date), sa.column('contract_id', sa.Integer),
        sa.column('annual_cost', sa.Numeric),
    )
    contracts_t = sa.table(
        'contracts',
        sa.column('id', sa.Integer), sa.column('vendor_id', sa.Integer),
        sa.column('license_id', sa.Integer), sa.column('po_number', sa.String),
        sa.column('start_date', sa.Date), sa.column('end_date', sa.Date),
        sa.column('payment_frequency', sa.String), sa.column('auto_renewal', sa.Boolean),
        sa.column('annual_cost', sa.Numeric), sa.column('created_at', sa.DateTime),
    )

    # 2. Every license today has at most one contract - link it directly
    #    and copy that contract's annual_cost onto the license.
    existing = bind.execute(
        sa.select(contracts_t.c.id, contracts_t.c.license_id, contracts_t.c.annual_cost)
        .where(contracts_t.c.license_id.isnot(None))
    ).fetchall()
    for c in existing:
        bind.execute(
            licenses_t.update().where(licenses_t.c.id == c.license_id).values(
                contract_id=c.id, annual_cost=c.annual_cost,
            )
        )

    # 3. Any license left with no contract gets one synthesized from its
    #    own existing fields (not fabricated data) so contract_id can be
    #    made required next.
    orphans = bind.execute(
        sa.select(
            licenses_t.c.id, licenses_t.c.vendor_id, licenses_t.c.po_number,
            licenses_t.c.start_date, licenses_t.c.expiration_date,
        ).where(licenses_t.c.contract_id.is_(None))
    ).fetchall()

    for row in orphans:
        start = row.start_date or date.today()
        end = row.expiration_date or (start + timedelta(days=365))
        result = bind.execute(
            contracts_t.insert().values(
                vendor_id=row.vendor_id,
                license_id=row.id,
                po_number=row.po_number or f"LEGACY-{row.id}",
                start_date=start,
                end_date=end,
                payment_frequency="Annual",
                auto_renewal=False,
                created_at=datetime.utcnow(),
            )
        )
        new_contract_id = result.lastrowid
        bind.execute(
            licenses_t.update().where(licenses_t.c.id == row.id).values(
                contract_id=new_contract_id, annual_cost=0,
            )
        )

    # 4. Now that every license has a contract, tighten the column and add
    #    its FK.
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.alter_column('contract_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index('ix_licenses_contract_id', ['contract_id'])
        batch_op.create_foreign_key('fk_licenses_contract_id_contracts', 'contracts', ['contract_id'], ['id'])

    # 5. Drop the now-redundant columns on the old (License-owns-Contract)
    #    side.
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contracts_license_id_licenses', type_='foreignkey')
        batch_op.drop_index('ix_contracts_license_id')
        batch_op.drop_column('license_id')
        batch_op.drop_column('annual_cost')


def downgrade():
    # Best-effort reverse. Lossy if any contract has picked up more than
    # one license since upgrading - only the lowest-id license per contract
    # is restored as that contract's license_id; every other license under
    # that contract is left pointing at a contract row that no longer
    # references it back.
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('license_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('annual_cost', sa.Numeric(precision=12, scale=2), nullable=True))

    bind = op.get_bind()
    licenses_t = sa.table(
        'licenses',
        sa.column('id', sa.Integer), sa.column('contract_id', sa.Integer),
        sa.column('annual_cost', sa.Numeric),
    )
    contracts_t = sa.table(
        'contracts',
        sa.column('id', sa.Integer), sa.column('license_id', sa.Integer),
        sa.column('annual_cost', sa.Numeric),
    )

    rows = bind.execute(
        sa.select(licenses_t.c.id, licenses_t.c.contract_id, licenses_t.c.annual_cost)
        .order_by(licenses_t.c.contract_id, licenses_t.c.id)
    ).fetchall()
    seen_contracts = set()
    for row in rows:
        if row.contract_id in seen_contracts:
            continue
        seen_contracts.add(row.contract_id)
        bind.execute(
            contracts_t.update().where(contracts_t.c.id == row.contract_id).values(
                license_id=row.id, annual_cost=row.annual_cost,
            )
        )

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('license_id', existing_type=sa.Integer(), nullable=False)
        batch_op.create_index('ix_contracts_license_id', ['license_id'])
        batch_op.create_foreign_key('fk_contracts_license_id_licenses', 'licenses', ['license_id'], ['id'])

    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_licenses_contract_id_contracts', type_='foreignkey')
        batch_op.drop_index('ix_licenses_contract_id')
        batch_op.drop_column('contract_id')
        batch_op.drop_column('annual_cost')
