"""Move license_type, annual_cost, vendor_contact to Contract

Revision ID: 921ad6913d0d
Revises: 11473ab5db73
Create Date: 2026-08-30 18:06:18.779056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '921ad6913d0d'
down_revision = '11473ab5db73'
branch_labels = None
depends_on = None


def upgrade():
    # contract_amount -> annual_cost is a rename, not a drop+add, so
    # existing contract values are preserved rather than discarded.
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'license_type', sa.String(length=30), nullable=False, server_default='Subscription'
        ))
        batch_op.add_column(sa.Column('vendor_contact', sa.String(length=150), nullable=True))
        batch_op.alter_column('contract_amount', new_column_name='annual_cost',
                               existing_type=sa.Numeric(precision=12, scale=2))
        batch_op.alter_column('license_type', server_default=None)

    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.drop_column('license_type')
        batch_op.drop_column('contract_number')
        batch_op.drop_column('annual_cost')
        batch_op.drop_column('vendor_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('software', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_contact', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('annual_cost', mysql.DECIMAL(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('contract_number', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('license_type', mysql.VARCHAR(length=30), nullable=False, server_default='Subscription'))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('annual_cost', new_column_name='contract_amount',
                               existing_type=sa.Numeric(precision=12, scale=2))
        batch_op.drop_column('vendor_contact')
        batch_op.drop_column('license_type')

    # ### end Alembic commands ###
