"""Replace contract_number with po_number as the contract identifier

Revision ID: 9a8022bc8924
Revises: 1e0c0fd5423f
Create Date: 2026-08-31 20:13:04.609877

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a8022bc8924'
down_revision = '1e0c0fd5423f'
branch_labels = None
depends_on = None


def upgrade():
    # Backfill po_number from contract_number wherever a contract has no
    # PO number of its own, so no existing identifying value is lost before
    # contract_number is dropped and po_number becomes required.
    contracts = sa.table('contracts', sa.column('id', sa.Integer),
                          sa.column('po_number', sa.String), sa.column('contract_number', sa.String))
    op.execute(
        contracts.update()
        .where(contracts.c.po_number.is_(None))
        .values(po_number=contracts.c.contract_number)
    )

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('po_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_contracts_contract_number'))
        batch_op.create_index(batch_op.f('ix_contracts_po_number'), ['po_number'], unique=False)
        batch_op.drop_column('contract_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_number', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_contracts_po_number'))
        batch_op.create_index(batch_op.f('ix_contracts_contract_number'), ['contract_number'], unique=False)
        batch_op.alter_column('po_number',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    contracts = sa.table('contracts', sa.column('id', sa.Integer),
                          sa.column('po_number', sa.String), sa.column('contract_number', sa.String))
    op.execute(contracts.update().values(contract_number=contracts.c.po_number))

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('contract_number', existing_type=mysql.VARCHAR(length=100), nullable=False)

    # ### end Alembic commands ###
