"""Move Annual Cost from License back to Contract

Revision ID: d28f530a8ef1
Revises: 7a1b4a3359c3
Create Date: 2026-09-01 12:00:00.000000

Reverses the License-level annual_cost introduced in 7a1b4a3359c3. Per-
license cost tracking (cost_per_license, unused_license_cost) is dropped
entirely rather than reapportioned - Annual Cost is once again a single
total per Contract. Hand-written (not autogenerated) to backfill
contracts.annual_cost from the licenses currently under each contract
before licenses.annual_cost is dropped, so no existing cost data is lost.
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd28f530a8ef1'
down_revision = '7a1b4a3359c3'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_cost', sa.Numeric(precision=12, scale=2), nullable=True))

    licenses_t = sa.table(
        'licenses', sa.column('id', sa.Integer), sa.column('contract_id', sa.Integer),
        sa.column('annual_cost', sa.Numeric),
    )
    contracts_t = sa.table(
        'contracts', sa.column('id', sa.Integer), sa.column('annual_cost', sa.Numeric),
    )

    # Every contract today has at most one license, so this is a clean
    # per-contract copy; if a contract has picked up more than one license,
    # their costs are summed into that contract's single total.
    rows = bind.execute(
        sa.select(licenses_t.c.contract_id, licenses_t.c.annual_cost)
    ).fetchall()
    totals = {}
    for row in rows:
        totals[row.contract_id] = totals.get(row.contract_id, 0) + (row.annual_cost or 0)
    for contract_id, total in totals.items():
        bind.execute(
            contracts_t.update().where(contracts_t.c.id == contract_id).values(annual_cost=total)
        )

    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_column('annual_cost')


def downgrade():
    bind = op.get_bind()

    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_cost', sa.Numeric(precision=12, scale=2), nullable=True))

    licenses_t = sa.table(
        'licenses', sa.column('id', sa.Integer), sa.column('contract_id', sa.Integer),
        sa.column('annual_cost', sa.Numeric),
    )
    contracts_t = sa.table(
        'contracts', sa.column('id', sa.Integer), sa.column('annual_cost', sa.Numeric),
    )

    # Best-effort: copies the whole contract total onto every license under
    # it (lossy/over-counting if a contract has more than one license).
    contracts = bind.execute(sa.select(contracts_t.c.id, contracts_t.c.annual_cost)).fetchall()
    for c in contracts:
        bind.execute(
            licenses_t.update().where(licenses_t.c.contract_id == c.id).values(annual_cost=c.annual_cost)
        )

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('annual_cost')
