# create_env.py
#
# Interactive setup script: generates a random SECRET_KEY, optionally
# provisions a MySQL database + dedicated user for production, and writes
# the resulting values to a .env file in the project root.
#
# Local development doesn't need this at all - config.py already falls
# back to a SQLite file under instance/ when DATABASE_URL is unset. Use
# this script when you're ready to point the app at MySQL/MariaDB.
import os
import secrets
import random
import string
from getpass import getpass

root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
env_path = os.path.join(root_path, ".env")

if os.path.exists(env_path):
    print(".env already exists in project root. Skipping write.")
    raise SystemExit(0)

secret_key = secrets.token_urlsafe(32)

use_mysql = input("Set up a MySQL database now? (y/N): ").strip().lower() == "y"

database_url = ""
if use_mysql:
    try:
        import pymysql
    except ImportError:
        print("PyMySQL is required for this step. Run `uv sync` first.")
        raise SystemExit(1)

    host = input("Enter MySQL host (default: localhost): ") or "localhost"
    root_user = input("Enter MySQL root username (e.g., root): ")
    root_pass = getpass("Enter MySQL root password: ")

    random_prefix = "".join(random.choices(string.ascii_lowercase + string.digits, k=5))
    database_name = f"{random_prefix}_licensehubk12"
    new_db_user = f"user_{random_prefix}"
    new_db_pass = secrets.token_urlsafe(16)

    connection = None
    try:
        connection = pymysql.connect(host=host, user=root_user, password=root_pass)
        cursor = connection.cursor()

        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {database_name}")
        cursor.execute(f"CREATE USER IF NOT EXISTS '{new_db_user}'@'%' IDENTIFIED BY '{new_db_pass}'")
        cursor.execute(f"GRANT ALL PRIVILEGES ON {database_name}.* TO '{new_db_user}'@'%'")
        cursor.execute("FLUSH PRIVILEGES")

        print(f"Database '{database_name}' created.")
        print(f"MySQL user '{new_db_user}' created.")

        database_url = f"mysql+pymysql://{new_db_user}:{new_db_pass}@{host}/{database_name}"
    except pymysql.MySQLError as e:
        print(f"MySQL Error: {e}")
        raise SystemExit(1)
    finally:
        if connection:
            connection.close()
else:
    print("Skipping MySQL setup - the app will use a local SQLite database.")

env_content = f"""# .env - generated by installation/create_env.py
SECRET_KEY={secret_key}
DATABASE_URL={database_url}

SESSION_COOKIE_SECURE=True
REMEMBER_COOKIE_SECURE=True
SESSION_TIMEOUT_MINUTES=60

RATELIMIT_STORAGE_URI=memory://

MAIL_SERVER=
MAIL_PORT=587
MAIL_USE_TLS=True
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_DEFAULT_SENDER=

SYNERGY_ENABLED=False
SYNERGY_BASE_URL=
SYNERGY_API_KEY=

CLEVER_ENABLED=False
CLEVER_CLIENT_ID=
CLEVER_CLIENT_SECRET=

CANVAS_ENABLED=False
CANVAS_BASE_URL=
CANVAS_API_TOKEN=

MAX_CONTENT_LENGTH_MB=5
UPLOAD_FOLDER=instance/uploads

LOG_LEVEL=INFO
"""

with open(env_path, "w") as f:
    f.write(env_content)

print(f".env file created at {env_path}")
if not use_mysql:
    print("Set SESSION_COOKIE_SECURE=False and REMEMBER_COOKIE_SECURE=False if running locally over plain HTTP.")
print("Next: uv run flask db upgrade   (then optionally: python installation/seed_data.py)")
